dungeons:
  pos:
    name: Pit of Saron
    url: https://keystone.guru/routes/retail/pit-of-saron
  academy:
    name: Algeth'ar Academy
    url: https://keystone.guru/routes/retail/algethar-academy
  skyreach:
    name: Skyreach
    url: https://keystone.guru/routes/retail/skyreach
  triumvirat:
    name: Seat of the Triumvirate
    url: https://keystone.guru/routes/retail/seat-of-the-triumvirate
  terrace:
    name: Magister's Terrace
    url: https://keystone.guru/routes/retail/magisters-terrace
  caverns:
    name: Maisara Caverns
    url: https://keystone.guru/routes/retail/maisara-caverns
  nexuspoint:
    name: Nexuspoint Xenas
    url: https://keystone.guru/routes/retail/nexuspoint-xenas
  spire:
    name: Windrunner Spire
    url: https://keystone.guru/routes/retail/windrunner-spire
